// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUNIWEB.Models;

namespace TUNIWEB.Migrations
{
    [DbContext(typeof(BB))]
    [Migration("20200514182140_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TUNIWEB.Models.Alumno", b =>
                {
                    b.Property<Guid>("idAlumno");

                    b.Property<string>("apMaterno");

                    b.Property<string>("apPaterno");

                    b.Property<string>("nombre");

                    b.HasKey("idAlumno");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("TUNIWEB.Models.areasCarrera", b =>
                {
                    b.Property<int>("idArea")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("area");

                    b.HasKey("idArea");

                    b.ToTable("catAreasCarrera");
                });

            modelBuilder.Entity("TUNIWEB.Models.carBeca", b =>
                {
                    b.Property<int>("noBeca")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("becaInstitucional");

                    b.Property<byte[]>("doc");

                    b.Property<Guid>("idUniversidad");

                    b.HasKey("noBeca");

                    b.HasIndex("idUniversidad");

                    b.ToTable("carBecas");
                });

            modelBuilder.Entity("TUNIWEB.Models.carreraTecnica", b =>
                {
                    b.Property<int>("noderelcat")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("catalogoCarrerasTecnicasId");

                    b.Property<Guid>("idAlumno");

                    b.HasKey("noderelcat");

                    b.HasIndex("idAlumno");

                    b.ToTable("carreraTecnicas");
                });

            modelBuilder.Entity("TUNIWEB.Models.catalogoCarrerasTecnicas", b =>
                {
                    b.Property<int>("idCarreTecnicas")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("carreraTecnica");

                    b.Property<int?>("relcart_Catnoderelcat");

                    b.HasKey("idCarreTecnicas");

                    b.HasIndex("relcart_Catnoderelcat");

                    b.ToTable("catalogoCarrerasT");
                });

            modelBuilder.Entity("TUNIWEB.Models.catalogoDeMapasCurriculares", b =>
                {
                    b.Property<int>("noDeMapaCurricular")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("doc");

                    b.Property<int>("idCarrera");

                    b.Property<Guid>("idUniversidad");

                    b.Property<string>("mapacurricular");

                    b.HasKey("noDeMapaCurricular");

                    b.HasIndex("idUniversidad");

                    b.ToTable("catalogoDeMapasCuarriculares");
                });

            modelBuilder.Entity("TUNIWEB.Models.catCarreras", b =>
                {
                    b.Property<int>("idCarrera")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("carreraImpartida");

                    b.Property<int>("idArea");

                    b.HasKey("idCarrera");

                    b.HasIndex("idArea")
                        .IsUnique();

                    b.ToTable("catCarreras");
                });

            modelBuilder.Entity("TUNIWEB.Models.contactos", b =>
                {
                    b.Property<int>("noDeContacto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contacto");

                    b.Property<Guid>("idUniversidad");

                    b.HasKey("noDeContacto");

                    b.HasIndex("idUniversidad");

                    b.ToTable("contactos");
                });

            modelBuilder.Entity("TUNIWEB.Models.DatosAcademicos", b =>
                {
                    b.Property<Guid>("idAlumno");

                    b.Property<string>("boletaGlobal");

                    b.Property<byte[]>("doc");

                    b.HasKey("idAlumno");

                    b.ToTable("datosAcademicos");
                });

            modelBuilder.Entity("TUNIWEB.Models.egreso", b =>
                {
                    b.Property<Guid>("idUniversidad");

                    b.Property<byte[]>("doc");

                    b.Property<string>("nivelEgreso");

                    b.HasKey("idUniversidad");

                    b.ToTable("egresos");
                });

            modelBuilder.Entity("TUNIWEB.Models.empresaAsociadas", b =>
                {
                    b.Property<int>("noDeEmpresaAsociada")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("empresaAsociada");

                    b.Property<Guid>("idUniversidad");

                    b.HasKey("noDeEmpresaAsociada");

                    b.HasIndex("idUniversidad");

                    b.ToTable("empresaAsociadas");
                });

            modelBuilder.Entity("TUNIWEB.Models.informacion", b =>
                {
                    b.Property<int>("idnoRecon")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("doc");

                    b.Property<Guid>("idAlumno");

                    b.Property<string>("reconocimiento");

                    b.HasKey("idnoRecon");

                    b.HasIndex("idAlumno");

                    b.ToTable("informaciones");
                });

            modelBuilder.Entity("TUNIWEB.Models.ingreso", b =>
                {
                    b.Property<Guid>("idUniversidad");

                    b.Property<byte[]>("doc");

                    b.Property<string>("metodoIngreso");

                    b.HasKey("idUniversidad");

                    b.ToTable("ingresos");
                });

            modelBuilder.Entity("TUNIWEB.Models.universidad", b =>
                {
                    b.Property<Guid>("idUnversidad");

                    b.Property<string>("direccion");

                    b.Property<string>("nombre");

                    b.HasKey("idUnversidad");

                    b.ToTable("universidades");
                });

            modelBuilder.Entity("TUNIWEB.Models.UsuarioAlumno", b =>
                {
                    b.Property<Guid>("idAlumno")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contraseña");

                    b.Property<string>("usuario");

                    b.HasKey("idAlumno");

                    b.ToTable("alumnosUsuarios");
                });

            modelBuilder.Entity("TUNIWEB.Models.UsuarioUniversidad", b =>
                {
                    b.Property<Guid>("idUniversidad")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("contraseña");

                    b.Property<string>("usuario");

                    b.HasKey("idUniversidad");

                    b.ToTable("universidadesUsuario");
                });

            modelBuilder.Entity("TUNIWEB.Models.Alumno", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioAlumno", "relAl_Us")
                        .WithOne("relUs_Al")
                        .HasForeignKey("TUNIWEB.Models.Alumno", "idAlumno")
                        .HasConstraintName("Relacion_usuario_alumno")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.carBeca", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relCB_USU")
                        .WithMany("relUSU_carB")
                        .HasForeignKey("idUniversidad")
                        .HasConstraintName("Relacion_usuario_becas")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.carreraTecnica", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioAlumno", "relCarrT_Al")
                        .WithMany("relUs_Cart")
                        .HasForeignKey("idAlumno")
                        .HasConstraintName("Relacion_usuario_carreraTecnica")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.catalogoCarrerasTecnicas", b =>
                {
                    b.HasOne("TUNIWEB.Models.carreraTecnica", "relcart_Cat")
                        .WithMany("relCat_cart")
                        .HasForeignKey("relcart_Catnoderelcat")
                        .HasConstraintName("Relacion_carreratecnica_catalogodecarrerastecnicas");
                });

            modelBuilder.Entity("TUNIWEB.Models.catalogoDeMapasCurriculares", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relCATCU_USU")
                        .WithMany("relUSU_CACU")
                        .HasForeignKey("idUniversidad")
                        .HasConstraintName("Relacion_usuario_CatalogoCurriculares")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.catCarreras", b =>
                {
                    b.HasOne("TUNIWEB.Models.areasCarrera", "relcarrarea")
                        .WithOne("relareacarr")
                        .HasForeignKey("TUNIWEB.Models.catCarreras", "idArea")
                        .HasConstraintName("Relacion_areac_carrera")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.contactos", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relC_USU")
                        .WithMany("relUSU_CON")
                        .HasForeignKey("idUniversidad")
                        .HasConstraintName("Rellacion_usuario_contacto")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.DatosAcademicos", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioAlumno", "Us_relDaac")
                        .WithOne("relDaac_Us")
                        .HasForeignKey("TUNIWEB.Models.DatosAcademicos", "idAlumno")
                        .HasConstraintName("Relacion_usuario_datosAcademicos")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.egreso", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relE_USU")
                        .WithOne("relUSU_E")
                        .HasForeignKey("TUNIWEB.Models.egreso", "idUniversidad")
                        .HasConstraintName("Relacion_usuario_egreso")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.empresaAsociadas", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relEA_USU")
                        .WithMany("relUSU_EA")
                        .HasForeignKey("idUniversidad")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.informacion", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioAlumno", "info_usuario")
                        .WithMany("rel_us_info")
                        .HasForeignKey("idAlumno")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.ingreso", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relI_USU")
                        .WithOne("relUSU_I")
                        .HasForeignKey("TUNIWEB.Models.ingreso", "idUniversidad")
                        .HasConstraintName("Relacion_usuario_ingreso")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TUNIWEB.Models.universidad", b =>
                {
                    b.HasOne("TUNIWEB.Models.UsuarioUniversidad", "relU_USU")
                        .WithOne("relUSU_U")
                        .HasForeignKey("TUNIWEB.Models.universidad", "idUnversidad")
                        .HasConstraintName("Relacion_usuarioUniversidad_universidad")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
